# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://a.hijoe.net
date_format: "ordinal"
title: 欢乐巴士
subtitle: "JoyBus.TK"
description: "欢迎来到欢乐巴士亲子社区，亲子经验交流，学习资源分享，愿在宝宝的成长路上，我们共同前行！"
keywords: 亲子, 启蒙, 教育, 资源,分享
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5
repository: bestop/joybus
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: true
# 组件配置
components:
    # 分享
    share:
        enabled: false
    # 不蒜子访问统计
    busuanzi:
        enabled: flase
        start_date: 2020-05-03
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 文章字数统计
word_count:
    enabled: true

# ---------------- #
#      Author      #
# ---------------- #
author: JoyBus
organization: 
organization_url: 
github_username: bestop
location: 3-12岁儿童通识启蒙教育
email: bestopjoe@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

#   -
#     href: /open-source/
#     label: 开源

  -
    href: /wiki/
    label: 频道

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: mzlogin1
    repo: blog-comments1
    oauth:
        client_id: d2e1cbbd2989580764621
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c3757091
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: mzlogin1
    repo: blog-comments1
    clientID: d2e1cbbd2989580764621
    clientSecret: b42a4178e5fd4a7cf63189ef4b1453b05c3757091
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: UA-80669434-11
    adsense:
        footer: true
        sidebar: true 
        content_header: true
        content_footer: false
